# Generated by Django 5.2.2 on 2025-06-06 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='purchase_date',
            new_name='purchased_at',
        ),
        migrations.AlterUniqueTogether(
            name='purchase',
            unique_together={('user', 'project')},
        ),
        migrations.AlterField(
            model_name='purchase',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='price_paid',
        ),
    ]
