# Generated by Django 5.2.2 on 2025-06-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_category_project_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('mobile', 'Aplicación Móvil'), ('web', 'Aplicación Web'), ('game', 'Juego'), ('dashboard', 'Dashboard'), ('ai', 'IA / Machine Learning'), ('script', 'Script / Automatización')], max_length=20),
        ),
    ]
